using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum BoonType {

	SACRIFICE_BONUS_XP,
	SACRIFICE_BONUS_HEALING,
	SACRIFICE_BONUS_FOOD,
	SURPLUS_FOOD_TO_BIRTHRATE,
	SURPLUS_FOOD_TO_HEALING,
	WARRIOR_CHILD_PROTECT,
	SAME_PROFESSION_XP_BONUS,
	SAME_PROFESSION_XP_REQ,
	PROFESSION_CHANGE_RETAIN_XP,
	MAX_VALUE
}
